### ISSUE TITLE
ScalarHeatDisplays don’t update while paused. 

### ISSUE THREAD

**Issue by davidson16807** [davidson16807/tectonics.js#11]
Posting here after being mentioned on issue #10

**Comment by davidson16807** [comment]
Pushed a fix to prod. Anyone here who can verify?

**Comment by astrographer** [comment]
It looks like you got the scalar display problem fixed. The time no longer shows.

**Comment by astrographer** [comment]
Also, I can say in passing that save is working for me now.

**Comment by davidson16807** [comment]
OK, thanks for letting me know.
