### ISSUE TITLE
Air temperature and precipitation displays aren't animated

### ISSUE THREAD

**Issue by astrographer** [davidson16807/tectonics.js#13]
On Firefox 56.0.2 Mac OS 10.12.6. The precipitation and temperature displays don't animate. They will update when I go to another display and go back, but they are static.

**Comment by davidson16807** [comment]
Fix is out. I was coincidentally working on temperature recently, so there's some other features released.

**Comment by astrographer** [comment]
Congratulations, it looks to be fixed.

**Comment by davidson16807** [comment]
Thanks Collin!
