### ISSUE TITLE
Load map into simulation

### ISSUE THREAD

**Issue by davidson16807** [davidson16807/tectonics.js#15]
Got this from an email, user doesn't have a git hub account so I'm posting it on his behalf:

>I am a worldbuilder with a map of a planet which I made with the aid of photshop and fractals which I really like - I have even divided it into rather simplistic plates - but, I would like to be able to take a raster picture of that map, load it into tectonics.js, and run it either forward *or backward*. Particularly backward, since I know how I want the planet to end up looking... just not how it got that way...

So there's two things going on here: 

* **Load map images into simulator** This is an idea I really like and I think it will help a lot while trying to validate the climate model from issue #9 . The issue I'm writing here will be limited in scope to this bullet point.

* **use the simulator to work backwards in time** This is a lot harder and it has a different priority, so I'm going to make a separate issue for this one: issue #16

**Comment by astrographer** [comment]
Loading a map for simulation would be very useful. I'd definitely support that!

Backwards sim would be awesome, but it's clearly going to eat up valuable dev time. Given the opportunity cost and lesser value, I agree with putting that pretty far back on the back burner…

**Comment by davidson16807** [comment]
I'm prioritizing this story since it plays well with a lot of other recent pertinent issues, namely #9, #34, and #37.

**Comment by davidson16807** [comment]
Won't be long 😁
![earth](https://user-images.githubusercontent.com/5824741/54721307-a24cd080-4b2f-11e9-93c3-97c0970be72a.png)

**Comment by davidson16807** [comment]
This is out in prod.

Still needs more documentation, but I think this is sufficient to close out the story. 

Some notes for future documentation:

* size of the uploaded image doesn't matter, just as long as it uses an equirectangular projection
* color doesn't matter, if the image is colored it will determine height from the brightness of the colors
* max and min height goes from the depth of the Marianas trench (black) to Mt. Everest (white)

**Comment by DrBrad22** [comment]
@davidson16807 seed/file for that map of the Earth?

**Comment by liracheer** [comment]
I just need the seed for the map of earth.

**Comment by davidson16807** [comment]
It's not a seed, you just drag and drop an image file and it will load it as a height map. Black and white gives best results, but IIRC it only reads the red color channel. The screenshot above was generated using a file that's in the tectonics.js repo, under tests/earth-heightmap.png.
