### ISSUE TITLE
Toggle Ice Off for Elevation map

### ISSUE THREAD

**Issue by astrographer** [davidson16807/tectonics.js#2]
The ice display interferes with the usefulness of the elevation display. If it could be toggled on/off, perhaps the same way as sea level display, that would greatly enhance the usefulness of the map.

As with sea level, toggling might prove useful for other display modes as well.

**Comment by davidson16807** [comment]
The best solution for this is to decouple the shader code used for satellite inspired imagery from the shader code used for representational maps. Commit 560bfdb executes this decoupling.

**Comment by davidson16807** [comment]
I'm going to close this unless there's something else to add here.

**Comment by astrographer** [comment]
It looks to be working. Not the way I did it in the home game, but it works.
