### ISSUE TITLE
Have elevation view respect Oceans option

### ISSUE THREAD

**Issue by seanth** [davidson16807/tectonics.js#32]
It looks like the "elevation" display option sets black to be 0 (sea level) whether you selection the Ocean display option as on or off. It would be great to be able to see elevation details under water, too.

**Comment by davidson16807** [comment]
I'll be doing some travel throughout most of September. Will address this as soon as possible.

**Comment by davidson16807** [comment]
Quick follow up: I'm revamping view logic within the app to support rendering multiple planets and a dev tool for raster visualization. There's significant tech debt in the view logic and it'll be easier to address this once the tech debt is taken care of.

**Comment by davidson16807** [comment]
This is addressed as of 65b0bfbd39603d6b2250ab4a6b2eb3a96dd6d4fb. Still need to push to prod.

**Comment by davidson16807** [comment]
This has been pushed to prod. Let me know if you notice issues with the implementation. Otherwise, I'm going to close this story out.
