### ISSUE TITLE
not working functions

### ISSUE THREAD

**Issue by username1234567890987654321** [davidson16807/tectonics.js#35]
I noticed that air pressure, precipitation and wind speed are not working.

**Comment by davidson16807** [comment]
Confirmed, will look into this.

**Comment by davidson16807** [comment]
Looks like the names for a few displays were borked during an earlier batch rename. Will push a fix for this by end of day.

**Comment by davidson16807** [comment]
Fixes have been deployed. Let me know if there are any more problems, otherwise I'll close out the issue.

**Comment by IsaacEthington** [comment]
Precipitation still doesn't seem to work. It shows colors, but only the default color lines and they do not change over time.

**Comment by davidson16807** [comment]
Nah, that's intended (unfortunately). We still need to work on precipitation. I'll prioritize that in another issue.

**Comment by davidson16807** [comment]
Issue #37 is created to address precip. I'm making a call for suggestions there.
