### ISSUE TITLE
Broken ocean overlay on plates view 

### ISSUE THREAD

**Issue by eojjn** [davidson16807/tectonics.js#39]
I've found that the ocean overlay is buggy on the plates view. Disabling and reenabling  it seems to fix it though.

**Comment by davidson16807** [comment]
Hrm, how so? Is it something you could capture in a screenshot. Are there steps to reproduce the issue?

**Comment by eojjn** [comment]
Hey, yes here are some screenshots
![erabype-250My(2)](https://user-images.githubusercontent.com/12370687/54274212-ca648e80-4587-11e9-8cc7-0233bf1b1407.png) on entering plates view
![erabype-250My(3)](https://user-images.githubusercontent.com/12370687/54274213-ca648e80-4587-11e9-866a-4e19776d6a68.png) after clicking play and then pause quick so map hasn't changed other than the ocean overlay correcting itself
![erabype-250My(4)](https://user-images.githubusercontent.com/12370687/54274271-f122c500-4587-11e9-826a-6e6aea8332e9.png)satellite view for reference

**Comment by eojjn** [comment]
I'm using Waterfox on Windows 10

**Comment by eojjn** [comment]
Also this is mainly noticeable when paused. It corrects itself after 30k years it seems on play

**Comment by davidson16807** [comment]
Confirmed, will look into this.

Steps to reproduce:

1. Pause the simulation
2. Switch to plate view

**Comment by davidson16807** [comment]
This has been fixed within f56545cb6d8f72d2d4a7012b9fc4ca8366dee768. The fixed is in prod, right now. Let me know if that doesn't work, otherwise I'll close the issue.
