### ISSUE TITLE
rockColumn 's default options density and thickness aren't defined

### ISSUE THREAD

**Issue by Estevo-Aleixo** [davidson16807/tectonics.js#6]
With the new optional system the variables "thickness" and "density" aren't defined globally. Should they be defined? Should they use the defaults in world.prototypes.ocean || world.prototypes.land ?
Perhaps I am building rockColumn 's wrong.

	this.thickness = optional['thickness'] || thickness;
	this.density =   optional['density']   || density;

**Comment by davidson16807** [comment]
Yes, that is a good catch. I didn't think too hard about optionals when I was setting up the save.

**Comment by davidson16807** [comment]
Commit 4a55507 fixes this. New defaults are defined by world.ocean. Both master and gh-pages should have this, now.

**Comment by Estevo-Aleixo** [comment]
I don't see any reason to keep this open.
