### ISSUE TITLE
Sealevel view after platerift

### ISSUE THREAD

**Issue by Estevo-Aleixo** [davidson16807/tectonics.js#7]
I ran the simulation with the Sealevel checkbox unchecked until a plate rifting event happened, Sealevel/waterlevel colors show up directly after a plate rifting event. Is this expected behavior?

![1432363730519-2 24by](https://cloud.githubusercontent.com/assets/723359/7782844/6978d90e-00f9-11e5-9abb-7ab0cebff235.png)

after reenabling the Sealevel checkbox

![1432363730519-2 24by 1](https://cloud.githubusercontent.com/assets/723359/7782857/c4f0a41a-00f9-11e5-9952-be405efaa580.png)

after re-unchecking the Sealevel checkbox

![1432363730519-2 24by 2](https://cloud.githubusercontent.com/assets/723359/7782864/e309b248-00f9-11e5-870a-6f94a3a67f6f.png)

These were all made by the screenshot utility / button included.

**Comment by davidson16807** [comment]
The fix works on my local machine. Should be live, now. If all works out well we can close.

**Comment by Estevo-Aleixo** [comment]
Works for me.
